In [2]:
import numpy as np

A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.8,135.0, 99.0, 0.9],
    [1.8, 135.0, 99.0, 0.9]
])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.8 135.   99.    0.9]
 [  1.8 135.   99.    0.9]]


In [16]:
cal = A.sum(axis =0)
print(cal)
print("type of cal", type(cal))
print("# of rows and cols", cal.shape)

# same, since cal is already 1 by 4 matirx

cal.reshape(1,4)
print(cal)
print("type of cal, reshaped", type(cal))
print("# of rows and cols, reshaped", cal.shape)


[ 59.6 270.  202.4  69.8]
type of cal <class 'numpy.ndarray'>
# of rows and cols (4,)
[ 59.6 270.  202.4  69.8]
type of cal, reshaped <class 'numpy.ndarray'>
# of rows and cols, reshaped (4,)


In [5]:
percentage = 100 * A /cal.reshape(1,4)
print(percentage)

[[93.95973154  0.          2.17391304 97.42120344]
 [ 3.02013423 50.         48.91304348  1.28939828]
 [ 3.02013423 50.         48.91304348  1.28939828]]


In [6]:
A / cal

array([[0.93959732, 0.        , 0.02173913, 0.97421203],
       [0.03020134, 0.5       , 0.48913043, 0.01289398],
       [0.03020134, 0.5       , 0.48913043, 0.01289398]])

In [8]:
pct = 100 * A / cal
print(pct)



[[93.95973154  0.          2.17391304 97.42120344]
 [ 3.02013423 50.         48.91304348  1.28939828]
 [ 3.02013423 50.         48.91304348  1.28939828]]


In [12]:
type(cal)
type(cal.reshape(1,4))

numpy.ndarray

In [20]:
np.array([
    [1,2,3],
    [4,5,6]
]) + np.array([[100]
, [200]])

array([[101, 102, 103],
       [204, 205, 206]])

In [37]:
a = np.random.randn(5) # don't use

#a = a.reshape(5,1)
b = np.random.randn(5,1)
b = np.random.randn(1,1)
#assert(a.shape == (5,1))
a.shape

(5,)

In [66]:
print(np.random.randn(2)) # normal distirbution
print(np.random.rand(2)) # uniform dist between 0 to 1

[-0.96627404 -1.40422478]
[0.74539198 0.57407623]


In [70]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
    
    Paramete